version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: grvapp-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: grvapp-backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata:

